apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble-ui-server
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hubble-oci.naser.cloud`)
      priority: 10
      services:
        - name: hubble-ui
          port: 80
  tls:
    secretName: letsencrypt-wildcard-cert-naser.cloud
