apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hakaya-dev
  namespace: hakaya-dev
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`hakaya-dev.snaya.org`)
      services:
        - name: hakaya-dev
          port: 80
  tls:
    secretName: letsencrypt-wildcard-cert-snaya.org
